backend:
  name: github
  repo: olekkram/Sky-Nova
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Страницы"
    folder: ""             
    create: false
    editable_files: true
    files:
      - file: "index.html"
        label: "Главная страница"
        name: "index"
        fields:
          - {label: "Вступительный текст", name: "intro", widget: "string"}
